namespace servos {
    //% block="servo P0" fixedInstance whenUsed
    export const P0 = new servos.PinServo(pins.P0);
    //% block="servo P0" fixedInstance whenUsed
    export const P1 = new servos.PinServo(pins.P1);
    //% block="servo P2" fixedInstance whenUsed
    export const P2 = new servos.PinServo(pins.P2);
    //% block="servo P3" fixedInstance whenUsed
    export const P3 = new servos.PinServo(pins.P3);
    //% block="servo C4" fixedInstance whenUsed
    export const C4 = new servos.PinServo(pins.C4);
    //% block="servo C5" fixedInstance whenUsed
    export const C5 = new servos.PinServo(pins.C5);
    //% block="servo C6" fixedInstance whenUsed
    export const C6 = new servos.PinServo(pins.C6);
    //% block="servo C7" fixedInstance whenUsed
    export const C7 = new servos.PinServo(pins.C7);
    //% block="servo C8" fixedInstance whenUsed
    export const C8 = new servos.PinServo(pins.C8);
    //% block="servo C9" fixedInstance whenUsed
    export const C9 = new servos.PinServo(pins.C9);
    //% block="servo C10" fixedInstance whenUsed
    export const C10 = new servos.PinServo(pins.C10);
    //% block="servo C11" fixedInstance whenUsed
    export const C11 = new servos.PinServo(pins.C11);
    //% block="servo C12" fixedInstance whenUsed
    export const C12 = new servos.PinServo(pins.C12);
    //% block="servo C13" fixedInstance whenUsed
    export const C13 = new servos.PinServo(pins.C13);
    //% block="servo C14" fixedInstance whenUsed
    export const C14 = new servos.PinServo(pins.C14);
    //% block="servo C15" fixedInstance whenUsed
    export const C15 = new servos.PinServo(pins.C15);
    //% block="servo C16 (A1 RX)" fixedInstance whenUsed
    export const C16 = new servos.PinServo(pins.C16);
    //% block="servo C17 (A1 TX)" fixedInstance whenUsed
    export const C17 = new servos.PinServo(pins.C17);
}