name: pxt-testghpkgs

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]
        branch: [stable3.0]

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          ref: ${{ matrix.branch }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          sudo npm install -g pxt
          npm install
      - name: pxt buildtarget
        run: pxt buildtarget
      - name: cache build output
        uses: actions/cache@f5ce41475b483ad7581884324a6eca9f48f8dcc7 # v1.2.1
        env:
          cache-name: cache-testghpkgs
        with:
          path: temp/ghpkgs
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-       
      - name: pxt testghpkgs
        run: pxt testghpkgs
        env:
          PXT_FORCE_GITHUB_PROXY: 1
          PXT_ACCESS_TOKEN: ${{ secrets.PXT_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_ACCESS_TOKEN }}
      - name: upload build log
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        if: ${{ always() }}
        with:
          name: logs-${{ matrix.branch }}
          path: temp/ghpkgs/*.txt
